# file: ponysay_install.yml
---
- name: Install Ponysay from source
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Installing CentOS dependencies
      ansible.builtin.yum:
        name: '{{item}}'
        state: latest
      when: ansible_distribution == 'CentOS'
      with_items:
      - 'automake'
      - 'epel-release'
      - 'git'
      - 'python36'
      - 'texinfo'

    - name: Installing Fedora Dependencies
      ansible.builtin.dnf:
        name: '{{item}}'
        state: latest
      when: ansible_distribution == 'Fedora'
      with_items:
      - 'automake'
      - 'git'
      - 'texinfo'

    - name: Installing Ubuntu dependencies
      ansible.builtin.apt:
        name: texinfo
        state: present
      when: ansible_distribution == 'Ubuntu'

    - name: Checking for current ponysay
      ansible.builtin.stat:
        path: '/bin/ponysay'
      register: ponysay

      ansible.builtin.debug:
        var: ponysay.stat.exists
 

    - name: Cloning ponysay repo and run install script
      when: not ponysay.stat.exists
      block:
        - name: Checking out repo from Github
          ansible.builtin.git:
            repo: https://github.com/erkin/ponysay.git
            dest: /tmp/ponysay
            version: master

        - name: Running the ponysay install script
          ansible.builtin.shell: |
            set -o pipefail
            /tmp/ponysay/setup.py --freedom=partial install
          args:
            chdir: /tmp/ponysay
            executable: /bin/bash
            creates: /bin/ponysay
...
# vim: ft=ansible:syntax=yaml.ansible:number:nowrap:relativenumber
