# file: ponysay_install.yml
---
- name: Install Ponysay from source
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Install CentOS dependencies
      ansible.builtin.yum:
        name: '{{item}}'
        state: latest
      when: ansible_distribution == 'CentOS'
      with_items:
      - 'automake'
      - 'epel-release'
      - 'git'
      - 'python36'
      - 'texinfo'

    - name: Install Fedora Dependencies
      ansible.builtin.dnf:
        name: '{{item}}'
        state: latest
      when: ansible_distribution == 'Fedora'
      with_items:
      - 'automake'
      - 'git'
      - 'texinfo'

    - name: Check for current ponysay
      ansible.builtin.stat:
        path: '/bin/ponysay'
      register: ponysay

    - name: See if its there
      debug:
        var: ponysay.stat.exists
 
    - name: Check out ponysay from Github
      ansible.builtin.git:
        repo: https://github.com/erkin/ponysay.git
        dest: '/tmp/ponysay'
      when: ponysay.stat.exists == false

    - name: Run the ponysay install script
      ansible.builtin.command: '/tmp/ponysay/setup.py --freedom=partial install'
      args:
        chdir: '/tmp/ponysay'
        creates: '/bin/ponysay'
      when: ponysay.stat.exists == false
...
# vim: ft=ansible:syntax=yaml.ansible:number:nowrap
